name: Jenkins Create Cluster Dev

on:
  workflow_dispatch:
jobs:
  call_reusable:
      - name: authentication info display
        run: printenv 
      - name: Read Project ID from dev.tfvars
        id: read_project
        shell: bash
        run: |
          PROJECT_ID=$(grep -E '^project_id' dev.tfvars | awk -F'=' '{print $2}' | tr -d ' "')
          if [ -z "$PROJECT_ID" ]; then
            echo "project_id not found in dev.tfvars"; exit 1
          fi
          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV
          echo "Detected project_id: $PROJECT_ID"
      - name: Run API check script
        run: |
          chmod +x ./check-apis.sh
          ./check-apis.sh $PROJECT_ID

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init 
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file=dev.tfvars
      - name: Terraform apply
        run: terraform apply -var-file=dev.tfvars -auto-approve       
